services:
  ct-archive-serve:
    image: colin-stubbs/ct-archive-serve:latest

    ports:
      # Default: expose container port 8080 on host 8080.
      - "8080:8080"
      # Optional: expose directly on host TCP/80.
      # - "80:8080"

    environment:
      - TZ=${TZ:-Etc/UTC}

      # Archive root inside the container (matches default in spec/tasks).
      - CT_ARCHIVE_PATH=${CT_ARCHIVE_PATH:-/var/log/ct/archive}
      - CT_ARCHIVE_FOLDER_PATTERN=${CT_ARCHIVE_FOLDER_PATTERN:-ct_*}

      # Optional: recommended when running behind a reverse proxy.
      #- CT_HTTP_TRUSTED_SOURCES="127.0.0.1/32"
      #- CT_HTTP_TRUSTED_SOURCES="192.168.1.0/24"

    volumes:
      # Put your downloaded `ct_*` folders under ./archive on the host. ct-archive-serve does not require more than read-only access.
      - ./archive:/var/log/ct/archive:ro

  qbittorrent:
    image: docker.io/qbittorrentofficial/qbittorrent-nox:latest
    environment:
      - TZ=${TZ:-Etc/UTC}
      - QBT_LEGAL_NOTICE=${QBT_LEGAL_NOTICE:-confirm}
      - PUID=65534
      - PGID=65534
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /path/to/your/config:/config
      - /path/to/your/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped